project:
  type: website
  output-dir: docs
  
website:
  title: "Ian Gray"
  navbar:
    background: primary
    right:
      - about.qmd
      - icon: github
        href: https://github.com/iangray22795
      - icon: linkedin
        href: https://linkedin.com/in/iangray27
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    embed-resources: true
    



