project:
  type: website

website:
  title: "myblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/IanGray22795
      - icon: twitter
        href: https://twitter.com/Vankor27
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



