---
title: "AWS s3 a New Way to Access Data"
author: "Ian Gray"
date: "2022-11-17"
categories: [Analysis, Project]
image: "Amazon-S3-Logo.svg"
---
# Storage to be Accessed From Anywhere
With a proper internet access you can pull and manipulate data from s3 with just a simple key.

# What is s3?

Simple, Storage, Service that is the expanded acronym for s3. In essence s3 or a s3 bucket is a simple storage provided as a service by cloud computing companies such as Amazon and Google. One of the most interesting things abour s3 is that it is a flat storage container although it looks very similar to your file system on your local computer. The one big difference is that when searching for files in s3 a program will see all files even if they are contained in a folder.

# How is This Useful

Being a storage system that anyone with access can pull files from and uopload files to and have the same structure to read files into programs is valuable enough. It also is extremely cheap for business use as 1TB coud run you a maximum of $10 a month. The support for R and Python through packages that have been built is useful for data science and data analytics work.

# DuckDB and s3
DuckDB has extensions, that will eventually be included in the base package, to connect directly to a s3 bucket. Just by setting the bucket name, pass key, and secret pass key if applicable you can pull all data from the s3 bucket to analyze and manipulate using duckdb.

```{.py filename=s3_start_up.py}
#first we build the the database
pip install duckdb==0.6.0
import duckdb as db
DB = db.connect(database = ":memory:", read_only = False)

#note: as of this post the extension is non functional in R but works in python
DB.execute("""INSTALL httpfs;
                 LOAD httpfs""")
#set access variables
DB.execute("""SET s3_region = 'region of bucket';
              SET s3_access_key_id = 'AWS access key id';
              SET s3_secret_access_key = 'AWS secret access key';""")

DB.execute("SELECT * FROM parquet_scan('s3:''bucket_name/*.parquetZ')")
```

# Arrow and s3

Another common way to interact with s3 is using the arrow package in R or Python. this is useful in R right now since duckdb extension crashes the r terminal. The Arrow package is also useful for other data wrangling features as well.

```{.r filename=using_arrow.r}
install.packages("arrow")
library(arrow)
#this returns a dataframe of each object in the s3 bucket
get_bucket_df(bucket = 's3://my-bucket/')
#pulls data from s3 of a specific type an error will be thrown if there are files of different types in the s3 storage
open_dataset(source = 's3://my-bucket/', format = 'file type')
```